import { afterEach, describe, expect, it } from 'vitest';
import type { ActorSystem } from '../actor-system.js';
import { createActorSystem } from '../actor-system-impl.js';
import { parse } from '../utils/factories.js';

const noopBehavior = {
  onMessage: async () => undefined,
};

const systemsToStop: ActorSystem[] = [];

async function startSystem(nodeAddress: string, maxActors?: number): Promise<ActorSystem> {
  const system = createActorSystem({ nodeAddress, maxActors });
  await system.start();
  systemsToStop.push(system);
  return system;
}

afterEach(async () => {
  await Promise.all(
    systemsToStop.splice(0).map(async (system) => {
      if (system.isRunning()) {
        await system.stop();
      }
    })
  );
});

describe('runtime ownership', () => {
  it('does not share autogenerated actor ids across same-node systems', async () => {
    const firstSystem = await startSystem('shared-node');
    const secondSystem = await startSystem('shared-node');

    const firstActor = await firstSystem.spawn(noopBehavior);
    const secondActor = await secondSystem.spawn(noopBehavior);
    const explicitActor = await secondSystem.spawn(noopBehavior, { id: 'explicit-id' });

    expect(parse(firstActor.address).id).not.toBe(parse(secondActor.address).id);
    expect(parse(explicitActor.address).id).toBe('explicit-id');
  });

  it('enforces maxActors per system instead of process-wide', async () => {
    const firstSystem = await startSystem('shared-node', 3);
    const secondSystem = await startSystem('shared-node', 3);

    await expect(firstSystem.spawn(noopBehavior)).resolves.toBeDefined();
    await expect(secondSystem.spawn(noopBehavior)).resolves.toBeDefined();
    await expect(firstSystem.spawn(noopBehavior)).rejects.toThrow('Maximum actor limit reached: 3');
  });

  it('reports totalActors per system from live instance-owned state', async () => {
    const firstSystem = await startSystem('shared-node');
    const secondSystem = await startSystem('shared-node');

    const firstExtraActor = await firstSystem.spawn(noopBehavior);
    await secondSystem.spawn(noopBehavior);
    await secondSystem.spawn(noopBehavior);

    await firstExtraActor.stop();

    await expect(firstSystem.getSystemStats()).resolves.toMatchObject({
      totalActors: 2,
    });
    await expect(secondSystem.getSystemStats()).resolves.toMatchObject({
      totalActors: 4,
    });
  });
});
